# Generated by Django 5.2.4 on 2025-08-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_counting'),
        ('resources', '0002_remove_resource_updated_at_resource_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assign_project',
            field=models.ForeignKey(blank=True, help_text='Single resource assigned to this project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assigned_to', to='resources.resource'),
        ),
    ]
