# Generated by Django 5.2.4 on 2025-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_assign_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project'), ('HOURLY_PROJECT', 'Hourly Project')], default='REGULAR', max_length=20),
        ),
    ]
