# Generated by Django 5.2.4 on 2025-08-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_project_type"),
        ("resources", "0002_remove_resource_updated_at_resource_counting"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                help_text="Poc assigned to this project (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poc",
                to="resources.resource",
            ),
        ),
    ]
