# Generated by Django 5.2.4 on 2025-08-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_poc"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
    ]
