# Generated by Django 5.2.4 on 2025-08-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_resource_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together=set(),
        ),
    ]
